version: '3'

services:
  catalog-server:
    build:
      context: .
      target: production
    volumes:
      - ./src/catalog-service:/app/src/catalog-service:ro
      - ./src/nginx:/app/src/nginx:ro
      - ./src/catalog-service/database.db:/app/database.db:rw
    environment:
      - PORT=3005
      - NODE_ENV=production
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s

  order-server:
    build:
      context: .
      target: production1
    volumes:
      - ./src/order-service:/app/src/order-service:ro
      - ./src/nginx:/app/src/nginx:ro
    environment:
      - PORT=3006
      - NODE_ENV=production1
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s

  client:
    build:
      context: .
    volumes:
      - ./src/client-service:/app/src/client-service:ro
    environment:
      - PORT=3007
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8083:80'
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - catalog-server
      - order-server
      - client

  redis:
    image: redis
